import bamboCategory from "./images/bamboo.jpg"
import stoolCategory from "./images/stools.jpg"
import sofaCategory from "./images/sofaset.jpg"
import newbornBlackCradle from "./images/newbornBlackCradle.jpg"
import newBornBasket from "./images/basket.jpg"
import newBornPinkCradel from "./images/newBornPinkCradel.jpg"
import babyChair from "./images/babyChair.jpg"
import bambooSofa from "./images/bambooSofa.jpg"
import tray from "./images/tray.jpg"
import RexineChair from "./images/RexineChair.png"
import hangingLight from "./images/hangingLight.jpg"
import petbedchair from "./images/puppybed.jpg"





const data = [
    {
      id: "recZkNf2kwmdBcqd0",
      name: "Newborn Photography Prop Cradle",
      price: 25,
      lastPrice :35,
      image:
      newbornBlackCradle,
      colors: ["#ff0000", "#00ff00", "#0000ff"],
      company: "Ecowoodies",
      reviews: 29,
      featured: false,
      feature1:"Eco-friendly",
      feature2:"Customized",
      feature3:"Material - Cane",
      feature4:"100% Recycle",
      feature5:"Customized Packaging",
      feature6:"Modern Stylish",
      description:
        "Our Newborn Photography Prop Cradle is a stunning, handcrafted piece of furniture that is perfect for both photo shoots and nurseries. Made from natural bamboo, sarkanda, wicker, and cane materials, this cradle is not only beautiful but also eco-friendly. The soft cushioning provides a comfortable and safe place for newborns to rest during their first few weeks of life, and it's the perfect prop for capturing those precious early memories.       The unique design of our cradle adds a touch of natural charm to any photography session or nursery decor. Whether you're a professional photographer or a new parent, this cradle will make a beautiful addition to your collection of baby props. It is sturdy and durable, so you can be sure it will last for years to come  We take pride in our commitment to sustainability, and our Newborn Photography Prop Cradle is a testament to that commitment. By using natural materials, we are able to create beautiful, functional furniture without harming the environment. When you purchase our cradle, you can feel good knowing that you're making a responsible choice for your family and for the planet.      Invest in this timeless and sustainable piece, and capture memories that will last a lifetime. Order your Newborn Photography Prop Cradle today and elevate your photography game!",
      category: "NewBorns",
      shipping: true,
      amount: 1,
      stock: 4,
    },
    {
      id: "recEHmzvupvT8ZONH",
      name: "Newborn Photography Prop Basket",
      price: 17,
      lastPrice :24,
      image:
      newBornBasket,
      colors: ["#000", "#ffb900"],
      company: "Ecowoodies",
      reviews: 19,
      featured: false,
      feature1:"Eco-friendly",
      feature2:"Customized",
      feature3:"Material - Cane",
      feature4:"100% Recycle",
      feature5:"Customized Packaging",
      feature6:"Modern Stylish",
      description:
        "Our Newborn Photography Prop Basket is a beautiful and versatile prop that is perfect for capturing those precious early memories. Handcrafted from natural bamboo, sarkanda, wicker, and cane materials, this basket is not only stunning but also eco-friendly. With its soft cushioning, the basket provides a comfortable and safe place for newborns to rest during photo shoots. Its unique design adds a touch of natural charm to any photography session or nursery decor. You can use it to create beautiful, whimsical scenes or classic, timeless portraits.     At our furniture manufacturing company, we pride ourselves on our commitment to sustainability. Our Newborn Photography Prop Basket is made from natural materials and crafted by hand, ensuring that each piece is unique and special. When you choose our basket, you're making a responsible choice for your family and for the planet. Invest in this beautiful and eco-friendly prop, and elevate your photography game. Order your Newborn Photography Prop Basket today and capture memories that will last a lifetime.",
      category: "NewBorns",
      shipping: true,
      amount: 1,
      stock: 4,
    },
    {
      id: "rec5NBwZ5zCD9nfF0",
      name: "Newborn Photography Prop Cradle",
      price: 24,
      lastPrice :35,
      image:
      newBornPinkCradel,
      colors: ["#ffb900", "#0000ff"],
      company: "Ecowoodies",
      reviews: 12,
      featured: false,
      feature1:"Eco-friendly",
      feature2:"Customized",
      feature3:"Material - Cane",
      feature4:"100% Recycle",
      feature5:"Customized Packaging",
      feature6:"Modern Stylish",
      description:
        "Our Red Newborn Photography Prop Cradle is a stunning addition to any photography studio or nursery. Handcrafted from natural bamboo, sarkanda, wicker, and cane materials, this cradle is not only beautiful but also eco-friendly. Its soft cushioning provides a comfortable and safe place for newborns to rest during photo shoots. The red color of the cradle adds a pop of boldness and fun to your photography sessions, making it a versatile prop that can be used for both classic and modern portraits. Its unique design adds a touch of natural charm to any photography session or nursery decor, making it a must-have for any new parent or photographer. We take pride in our commitment to sustainability, and our Red Newborn Photography Prop Cradle is a testament to that commitment. By using natural materials, we're able to create beautiful, functional furniture without harming the environment. When you purchase our cradle, you can feel good knowing that you're making a responsible choice for your family and for the planet. Invest in this timeless and sustainable piece, and capture memories that will last a lifetime. Order your Red Newborn Photography Prop Cradle today and elevate your photography game with a bold and stunning pop of color.",
      category: "NewBorns",
      amount: 1,
      stock: 4,
    },
    {
      id: "recd1jIVIEChmiwhe",
      name: "Bamboo Lounge Chair",
      price: 38,
      lastPrice :52,
      image: bamboCategory,
      colors: ["#000", "#00ff00", "#0000ff"],
      company: "Ecowoodies",
      reviews: 19,
      featured: true,
      feature1:"100% Eco-friendly",
      feature2:"Customized",
      feature3:"Material - Bamboo",
      feature4:"100% Recycle",
      feature5:"Customized Packaging",
      feature6:"Traditional",
      description:
        "Experience the ultimate in comfort and style with our handcrafted Bamboo Lounge Chair, made in the North East States of India. This chair is the perfect addition to any home, whether you're looking for a cozy reading nook or a relaxing spot to watch TV. Crafted from natural and sustainable bamboo materials, this lounge chair is not only beautiful but also eco-friendly. Its unique design provides optimal comfort, with a sturdy frame and soft cushions that cradle your body. At our furniture manufacturing company, we take pride in our commitment to sustainability and traditional craftsmanship. Each Bamboo Lounge Chair is meticulously handcrafted, ensuring that every piece is unique and of the highest quality. With its timeless design and natural materials, our Bamboo Lounge Chair is a versatile piece that can complement any decor. Whether you're going for a modern, minimalist look or a cozy, rustic feel, this chair is the perfect fit. Invest in sustainable and stylish furniture with our Bamboo Lounge Chair. Order yours today and add a touch of natural beauty to your home.",
      category: "BambooLoungeChair",
      shipping: true,
      amount: 1,
      stock: 4,
    },
    {
      id: "recoM2MyHJGHLVi5l",
      name: "Baby Chair",
      price: 20,
      lastPrice :28,
      image:
      babyChair,
      colors: ["#000"],
      company: "Ecowoodies",
      reviews: 65,
      featured: false,
      feature1:"100 %Eco-friendly",
      feature2:"Customized",
      feature3:"Material - Sarkanda",
      feature4:"100% Recycle",
      feature5:"Customized Packaging",
      feature6:"Soft Baby Chair for Photography",
      description:
        "Introducing our Sarkanda Baby Chair, handcrafted with love by local artisans of North India. Made from sustainable sarkanda materials, this chair is the perfect addition to your baby's nursery or any other cozy corner of your home. Our furniture manufacturing company takes pride in our commitment to sustainability and traditional craftsmanship. Each Sarkanda Baby Chair is handmade by local artisans, ensuring that every piece is unique and of the highest quality. Designed with both comfort and safety in mind, this chair provides optimal support for your baby while still being stylish and functional. Its natural materials and simple design complement any nursery decor, adding a touch of natural beauty to your home. Sarkanda is a durable and eco-friendly material that has been used for centuries to make furniture and other household items. By using sustainable materials, we're able to create beautiful, functional furniture without harming the environment. Invest in sustainable and stylish furniture with our Sarkanda Baby Chair. Order yours today and give your baby a safe and comfortable place to rest and play.",
      category: "NewBorns",
      shipping: true,
      amount: 1,
      stock: 4,
    },
    {
      id: "recotY5Nh00DQFdkm",
      name: "Hanging Light",
      price: 15,
      lastPrice :21,
      image:
      hangingLight,
      colors: ["#00ff00", "#0000ff", "#ff0000"],
      company: "Ecowoodies",
      reviews: 107,
      featured: false,
      feature1:"Eco-friendly",
      feature2:"Customized",
      feature3:"Material - Bamboo, Rattan, Cane",
      feature4:"100% Recycle",
      feature5:"Customized Packaging",
      feature6:"Modern",
      description:
        "Illuminate your space with our handcrafted Bamboo Hanging Light, made by skilled artisans from the North East States of India. Crafted from natural and sustainable bamboo materials, this light fixture adds a touch of warmth and elegance to any room in your home. Our furniture manufacturing company takes pride in our commitment to sustainability and traditional craftsmanship. Each Bamboo Hanging Light is meticulously handmade, ensuring that every piece is unique and of the highest quality. With its simple yet stylish design, this hanging light is the perfect addition to any home decor. The natural materials and intricate weaving techniques used in its creation give it a distinct character that sets it apart from other lighting options. Not only is bamboo a beautiful and durable material, but it's also an eco-friendly choice that helps reduce your carbon footprint. By choosing sustainable materials, you can make a positive impact on the environment while still enjoying beautiful and functional furniture. Invest in sustainable and stylish lighting with our Bamboo Hanging Light. Order yours today and add a touch of natural beauty to your home.",
      category: "Lighting",
      shipping: true,
      amount: 1,
      stock: 4,
    },
    {
      id: "rec1Ntk7siEEW9ha1",
      name: "Bamboo 5 Seater Sofa",
      price: 125,
      lastPrice :145,
      image:
      bambooSofa,
      colors: ["#0000ff", "#000"],
      company: "Ecowoodies",
      reviews: 35,
      featured: false,
      feature1:"Eco-friendly",
      feature2:"Customized",
      feature3:"Material - Bamboo",
      feature4:"100% Recycle",
      feature5:"Customized Packaging",
      feature6:"Usage - Hotels And office",
      description:
        "Experience the beauty of natural and sustainable materials with our handcrafted Bamboo 5 Seater Sofa Set, made by skilled artisans from the North East States of India. This elegant and durable furniture set is the perfect addition to your living room, adding both comfort and style to your home. Our furniture manufacturing company takes pride in our commitment to sustainability and traditional craftsmanship. Each piece in this sofa set is handmade with meticulous attention to detail, ensuring that every sofa is unique and of the highest quality. The bamboo used in this sofa set is a sustainable and eco-friendly material that's also known for its strength and durability. With proper care, your bamboo sofa set can last for years, making it a practical and cost-effective choice for your home. Not only is this sofa set beautiful and functional, but it also adds a touch of natural beauty to your living space. The natural grain and texture of the bamboo gives this set a unique character that sets it apart from other furniture options. Invest in sustainable and stylish furniture with our Bamboo 5 Seater Sofa Set. Order yours today and experience the natural beauty and durability of bamboo.",
      category: "BambooSofaSet",
      shipping: true,
      amount: 1,
      stock: 4,
    },
    {
      id: "recNZ0koOqEmilmoz",
      name: "Cane 5 Seater Sofa",
      price: 110,
      lastPrice :135,
      image:
       sofaCategory,
  
      colors: ["#000", "#ff0000"],
      company: "Ecowoodies",
      reviews: 25,
      featured: true,
      feature1:"Eco-friendly",
      feature2:"Customized",
      feature3:"Material - Bamboo",
      feature4:"100% Recycle",
      feature5:"Customized Packaging",
      feature6:"Usage - Hotels And office",
      
      description:
        "Transform your living room with our handcrafted Cane 5 Seater Sofa Set, made with care by local artisans in North India. The set's unique design and durable construction are sure to impress, while its eco-friendly materials and ethical production practices make it a responsible choice for your home. Crafted from high-quality cane, this sofa set is strong and built to last. The natural texture and warm color of the cane lend it a timeless elegance that complements any decor style. Plus, because it's handmade, each sofa is one-of-a-kind, adding a touch of artistry to your living space. As a furniture manufacturing company that values sustainability, we're committed to using only responsibly sourced materials and ethical production practices. We partner with local artisans to ensure that our furniture is made with care and attention to detail, while also supporting the livelihoods of skilled craftspeople. The Cane 5 Seater Sofa Set is perfect for families and socializing, with plenty of room for everyone to relax in comfort. Its clean lines and simple design allow it to blend seamlessly with your existing decor, while its sturdy construction ensures it will stand the test of time. Upgrade your living room with our stylish and sustainable Cane 5 Seater Sofa Set. Order yours today and experience the beauty and quality of handmade furniture from North India. Regenerate response",
      category: "BambooSofaSet",
      shipping: true,
      amount: 1,
      stock: 4,
    },
    {
      id: "recrfxv3EwpvJwvjq",
      name: "Bakery Tray",
      price: 7,
      lastPrice :12,
      image:
      tray,
  
      colors: ["#000", "#00ff00"],
      company: "Ecowoodies",
      reviews: 27,
      featured: false,
      feature1:"Eco-friendly",
      feature2:"Customized",
      feature3:"Material - Bamboo",
      feature4:"100% Recycle",
      feature5:"EU Food Safety Certified",
      feature6:"Bakey & Dining",
      description:
        "Introducing our exquisite handmade Cane Bakery Tray, crafted with utmost care and attention by skilled local artisans from North India. Made with high-quality cane material, this tray exudes elegance, style, and durability, making it a perfect addition to your bakery or kitchen. The beautiful natural texture of the cane adds an element of warmth and sophistication to any setting, making it a great conversation starter among your guests. Its lightweight and sturdy design make it easy to carry around, while its large size makes it ideal for serving and displaying your delectable baked goods, pastries, and desserts. Our commitment to sustainable and eco-friendly practices is reflected in the use of cane, a renewable and biodegradable material that is gentle on the environment. Whether you're a professional baker or a home cook, this Cane Bakery Tray is a must-have for anyone who values style, functionality, and quality. Shop now and experience the beauty of handmade craftsmanship at its best.",
      category: "office",
      shipping: true,
      amount: 1,
      stock: 4,
    },
    {
      id: "recoW8ecgjtKx2Sj2",
      name: "Ottoman",
      price: 75,
      lastPrice :83,
      image:
        stoolCategory,
      colors: ["#ff0000", "#ffb900", "#00ff00"],
      company: "Ecowoodies",
      reviews: 230,
      featured: true,
      feature1:"Eco-friendly",
      feature2:"Customized",
      feature3:"Material - Bamboo",
      feature4:"100% Recycle",
      feature5:"Customized Packaging",
      feature6:"Usage - Hotels, Home and Cafe",
      description:
        "Introducing our stunning collection of Cane Ottomans, crafted by local artisans of North India using eco-friendly and recyclable materials. Each ottoman is unique and handmade, adding a touch of natural beauty to any living space. Our Cane Ottomans are the perfect addition to your home decor, providing a stylish and sustainable seating option. Made from high-quality cane, they are durable and sturdy, ensuring long-lasting use. The natural texture and color of the cane add a warm and cozy feeling to your living space. With its versatile design, our Cane Ottomans can be used as a footrest, extra seating or even as a small table. Its lightweight and compact design make it easy to move around and store when not in use. We take pride in our commitment to sustainability, and each of our Cane Ottomans is crafted using eco-friendly and recyclable materials. By choosing our handmade products, you are not only adding a unique and stylish piece to your home decor, but also contributing to a greener and more sustainable future. Add a touch of elegance and sustainability to your home with our beautiful collection of Cane Ottomans. Choose from our variety of sizes and designs to find the perfect fit for your home.",
      category: "Ottoman",
      amount: 1,
      stock: 4,
    },
    {
      id: "recoW8ecgjtKx2Sj2",
      name: "Pet Bed",
      price: 26,
      lastPrice :35,
      image:
      petbedchair,
      colors: ["#ff0000", "#ffb900", "#00ff00"],
      company: "Ecowoodies",
      reviews: 230,
      featured: true,
      feature1:"Eco-friendly",
      feature2:"Customized",
      feature3:"Material - Bamboo",
      feature4:"100% Recycle",
      feature5:"Customized Packaging",
      feature6:"Usage - Dogs, Kitty, Cats",
      description:
        "If you're looking for a cozy and eco-friendly bed for your furry friend, our handmade pet beds are just what you need. Crafted by skilled artisans in North India, these beds are not only stylish but also sustainable as they are made from natural and renewable bamboo materials. Our pet beds come in a variety of sizes and designs to fit your pet's unique needs and personality. The soft cushioning ensures maximum comfort and support for your pet, allowing them to rest peacefully after a long day of playing and exploring. Not only are these beds great for your pet, but they are also great for the environment. Bamboo is one of the most sustainable materials available, and our commitment to eco-friendliness means that we use only eco-friendly, recyclable materials in our products. Investing in our pet beds means that you're not only getting a high-quality product but also contributing to a better future for our planet. So give your pet the gift of comfort and sustainability with our handmade bamboo pet beds.",
      category: "PetBeds",
      amount: 1,
      stock: 4,
    },
  ];
  export default data;